# This workflows enables bumping minor version by tagging and updating package.json
name: Bump Workflow

on:
  workflow_call:
    secrets:
      gh_token:
        required: true
      gh_email: 
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name:  'Automated Version Bump'
        uses:  'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.gh_token }}
          GITHUB_EMAIL: ${{ secrets.gh_email }}
        with:
          default: minor
