# This workflows enables bumping minor version by tagging and updating package.json
#
# It follows semver and will bump the minor version by default
#
# You can also specify the version bump with commits
#
# Major: commit message contains "BREAKING CHANGE" or "major"
# Minor: commit message contains "feat" or "minor"
# Patch: commit message contains "fix" or "patch"
#
# You can add it to your workflow like this:
#
# name: Bump version
# on:
#   push:
#     branches:
#       - main
# jobs:
#   bump:
#     uses: ShapeGames/workflows/.github/workflows/bump-version.yml@main
#     secrets:
#       gh_token: ${{ secrets.GH_TOKEN }}
#       gh_email: ${{ secrets.GH_EMAIL }}
#     with:
#       semver_bump: minor

name: Bump Workflow
on:
  workflow_call:
    secrets:
      gh_token:
        required: true
      gh_email:
        required: true
    inputs:
      semver_bump:
        type: string
        default: minor
jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name:  'Automated Version Bump'
        uses:  'ShapeGames/gh-action-bump-version@v10.0.1'
        env:
          GITHUB_TOKEN: ${{ secrets.gh_token }}
          GITHUB_EMAIL: ${{ secrets.gh_email }}
        with:
          default: ${{ inputs.semver_bump }}
