name: Bump Workflow

on:
  workflow_call:
    secrets:
      gh_token:
        required: true
jobs:
  build:
    - name:  'Automated Version Bump'
      uses:  'phips28/gh-action-bump-version@master'
      env:
        GITHUB_TOKEN: ${{ secrets.gh_token }}
      with:
        default: minor
