# This workflows enables bumping minor version by tagging and updating package.json
name: Bump Workflow

on:
  workflow_call:
    secrets:
      gh_token:
        required: true
      gh_email:
        required: true
    inputs:
      semver_bump:
        type: string
        default: minor
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name:  'Automated Version Bump'
        uses:  'ShapeGames/gh-action-bump-version@v10.0.1'
        env:
          GITHUB_TOKEN: ${{ secrets.gh_token }}
          GITHUB_EMAIL: ${{ secrets.gh_email }}
        with:
          default: ${{ inputs.semver_bump }}
