on:
  workflow_call:
    secrets:
      HOST_ENV:
        required: false
      RELATIVE_CI_KEY:
        required: false
    inputs:
      node_version: 
        type: string
        default: 16
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      HOST_ENV: ${{ secrets.HOST_ENV }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node_version }}
      - uses: ShapeGames/npm-install@v1.8.34
      - uses: actions/cache@v3
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}
      - name: yarn build
        run: yarn build
        env:
          RELATIVE_CI_KEY: ${{ secrets.RELATIVE_CI_KEY }}
      - run: yarn test
 
