on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: ShapeGames/npm-install@v1.7.9
      - uses: actions/cache@v2
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}
      - run: yarn build
      - run: yarn test
      - uses: actions/upload-artifact@v1
        if: success()
        with:
          name: bundle-client.html
          path: .next/public/bundle-client.html
 
