on:
  workflow_call:
    secrets:
      HOST_ENV:
        required: false
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HOST_ENV: ${{ secrets.HOST_ENV }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: ShapeGames/npm-install@v1.7.9
      - uses: actions/cache@v3
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}
      - run: yarn build
      - run: yarn test
 
