name: Check for library template updates

on:
  workflow_call:
    inputs:
      script:
        required: true
        type: string
      branch:
        required: true
        type: string
    secrets:
      write_github_token:
        required: true
      git_username:
        required: true
      git_email:
        required: true

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install packages
        run: pnpm install

      - name: Configure git
        uses: xiplias/github-git-config-action@v1
        with:
          user.name: ${{ secrets.git_username }}
          user.email: ${{ secrets.git_email }}
          github-token: ${{ secrets.write_github_token }}
      
      - name: run script
        run: pnpm run ${{ inputs.script }}

      - name: cat
        run: cat .git/config

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.write_github_token }}
          commit-message: "feat: update from web-library-scripts"
          title: "feat: update from web-library-scripts"
          branch: ${{ inputs.branch }}
          base: "main"
          delete-branch: true
