on:
  workflow_call:
    secrets:
      gh_packages_token:
        required: true
      gh_token:
        required: true
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    outputs:
      published: ${{ steps.changesets.outputs.published }}
    env:
      GH_PACKAGES_TOKEN: ${{ secrets.gh_packages_token }}
      NPM_TOKEN: ${{ secrets.gh_packages_token }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 8
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm run version
          title: 'ci(root): release versions'
          commit: 'ci(root): release versions'
          publish: pnpm run release
        env:
          GITHUB_TOKEN: ${{ secrets.gh_token }}

  publish-kambi:
    name: Publish to Kambi Artifactory
    needs: release
    if: needs.release.outputs.published == 'true'
    runs-on: shape-games-kambi-hosted
    env:
      NPM_TOKEN: ${{ secrets.KAMBI_ARTIFACTORY_API_KEY }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Install PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 8
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Publish to Kambi Artifactory
        run: pnpm publish --registry https://artifactory.services.kambi.com/artifactory/api/npm/npm-shapegames/
