on:
  workflow_call:
    secrets:
      gh_packages_token:
        required: true
      gh_token:
        required: true
      federation_access_key_id:
        required: false
      federation_secret_key:
        required: false
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      GH_PACKAGES_TOKEN: ${{ secrets.gh_packages_token }}
      NPM_TOKEN: ${{ secrets.gh_packages_token }}
      AWS_ACCESS_KEY_ID: ${{ secrets.federation_access_key_id }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.federation_secret_key }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm run version
          title: "ci(root): release versions"
          commit: "ci(root): release versions"
          publish: pnpm run release
        env:
          GITHUB_TOKEN: ${{ secrets.gh_token }}
