#
# This workflow enables semantic releases with support for prereleases
#
# When you specify staging and preprod with the pre_release_branches variable and adding a commit on a pre-release branch
# the tagged version will be vX.X.X-{branch}.N
# 
# This enables a tag workflow where you can see the following:
#
# Example:
# v1.0.0-staging.0 <- commit on staging
# v1.0.0-staging.1 <- commit on staging
# v1.0.0-preprod.0 <- commit on preprod
# v1.0.0           <- commit on master/main
# v1.1.0-staging.0 <- commit on staging
#
# When tagging a commit it will also create a release with a changelog
# 

name: Release Workflow

on:
  workflow_call:
    secrets:
      gh_token:
        required: true
    inputs:
      release_branches:
        required: true
        type: string
      pre_release_branches:
        type: string
        required: true
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.github_token }}
          release_branches: ${{ inputs.release_branches }}
          pre_release_branches: ${{ inputs.pre_release_branches }}
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          generateReleaseNotes: true
