name: Renovate Workflow
on:
  workflow_call:
    secrets:
      token:
        required: true
      repos:
        required: true
jobs:
  renovate:
    concurrency: ci-${{ github.workflow }}-${{ github.repository }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.1.8
        with:
          token: ${{ secrets.token }}
        env:
          LOG_LEVEL: 'debug'
          RENOVATE_REPOSITORIES: ${{ secrets.repos }}
          GH_PACKAGES_TOKEN: ${{ secrets.token }}
          RENOVATE_EXPOSE_ALL_ENV: true
          NPM_TOKEN: ${{ secrets.token }}
