name: Renovate Workflow
on:
  workflow_call:
    secrets:
      token:
        required: true
      encryption_key:
        required: true
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v32.32.2
        with:
          configurationFile: .github/renovate-config.js
          token: ${{ secrets.token }}
        env:
          RENOVATE_PRIVATE_KEY: ${{ secrets.encryption_key }}
          LOG_LEVEL: 'debug'
