name: Bump version (only for use in this workflow repo)
on:
  push:
    branches:
      - main
jobs:
  workflow:
    uses: ShapeGames/workflows/.github/workflows/bump-version.yml@main
    secrets:
      gh_token: ${{ secrets.GH_TOKEN }}
      gh_email: ${{ secrets.GH_EMAIL }}
    with:
      semver_bump: minor
